apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0PEN8K9Xr3Jnn//sJkFumZM0E3mAg9G0/lyYF4uOB/+H003R27b3SA==,iv:IO32G5GsoQh8sb4mdyTsbuS5Q0zFJfYJA8Ahkj1u3LA=,tag:3fMOun2nmzLpXet6tkF4rQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiamlpTjN0dm1CcFVsYU5F
            ODFRSGVpcnZPSUI1NVZmTUROLy9OYXBjdnpnCldUYUpvWUN0alhueVpac2d3WXBC
            QWxoVUZXM1FxY2M1UjNGQmlDK1hzSEEKLS0tIHQrZFQxcFdMSDcyblVRRmRqYUg3
            b3ArM2lDb1d6V2dTRnpqSlArRmYzb00Ka/2TFmjG00SL/O6KYiFRmAPyMfGNgKsu
            l4IhzWYP0woesYq4dxsYYogf45TU3WPEW5+6fWEdwlxRmNI0rTmfPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-28T08:32:15Z"
    mac: ENC[AES256_GCM,data:M97YvU9Ns+aITd9PansIGIpkjZxF3zQni6woLNVI2Dg9Wc7kDs2imwWyrY8yy9dV4kFLY9NgTcSmEmDJtiG6V+w6VeqOQvDEtIcE5aB2tsBogGUACbJqj0Dkjkm5oCx8T1Q1205EBJeYmsZ+ou10e1lnnJxNjQqTZBM+A4IErmI=,iv:hARSa4p4PJDfrSTvJkMcp+/Hsfbz6Sg1DYqyiCPLuKA=,tag:fgz/wrweLw6bECkmtn8MfA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
