apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EgoxbqiZU8T+LY+OQotgRUGrhPkwjWAfMzrFnN6IqyB7lLg5hl3sQQ==,iv:8ghvJJgFPH5u9jQTywk06/duK1FBYJ5CiI/PQRfTSlw=,tag:ufuaAYidx8OEbm1/pLwdGQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZkxXaGN2a0dOOWhqUkk0
            SEs1bzBjeGY1YWI5UFhFV3NrQXpXSGxLNEZJCnhybk9YTXVxcmgzTURCU0srN0px
            bWtBUUZLZkp3eC8yQVgyT3RVYlQ2Q1kKLS0tIHh0cE1ObzRUdHZXSE9XM2U2S3Bt
            R3FYUXZKQjh1dEJXL3VLYnp1bkpEeXcKgJBSW03bn56k4eNDFC+eNIJbhgj6JKan
            SZFSupzpeQVKz71tFHmL7EBefyg8FeS98ol47/oBlw7qdooogIUfuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T10:44:22Z"
    mac: ENC[AES256_GCM,data:E3Hf8acJ3MvYcz0XjsYXJVvr6IWRIBp5pF44/Xotw6r688+i0UbflYvrnMbwwLtMV1rJwftTs7ioyd8DaOXphu49HBd15/wZ32iNmkEbdRo9eLD+/aGWgfh7Cal+aWTci9xQ/LNUYvWwidEnUq6RqaEHLD1J1Po3lw+gIAZ2Zv0=,iv:l8oIUrxPWaA+iRtm/PcnuKbVIwmTNzObCVt3n/H17Ak=,tag:JEy5g4j+QcU1M52A/KuQ1g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
