apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:X1OEc901xhDWuPo6fR5Xnwlk7IUldgr/IxGNgxJMkZgr84EMpM4nOw==,iv:hQviLP33vwMlJ++7tBnZuh3nqoLfl5ZBuZ/nCq2aVXI=,tag:qLOvmI40GiPl5lYeHGe4Vw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z2pvV0pjN3FCcW5SdEZV
            WE9sYzFlMXBIRFdtU29JVC9Gdi83dUNkR2xBCnlkUzhQRzdodEk0bm5qZ2NKaWlC
            MndaSWJ6REJEN0ZHWERzYStSNWhWZm8KLS0tIFg0ZHV1ckpweUU4ZHU5ZVJsbkYy
            ZlNYeGhLZ29KL01LZXhuS0gvOGx1ejgKx5YW3DRa/zlmBEAzP6hHFtMViCQ0b4ju
            Ps2SoFeBB+VGB4vdTjfFot77+eVX/bzC5fiw5dsISiyCoCBUuI22IA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-01T05:23:40Z"
    mac: ENC[AES256_GCM,data:u4kf/xF44PPMqV9iTMOoUlPDhjApifi70W2osXi+vDe/fdkhF+JHBpU73zGVaRrxLO3ETLWFpkLZ5TkZXVwL7FMv6gF4aJprOprdtESpt66Kq0g3xEUo2b/eJyBWHplz4bxutLCXV0Bg8ozDvQbjiZ4xKM2vVxODU8ErhcCcdfU=,iv:L2x87j4KXW34esnDQvNUXqINSyDQ6bugqIvb87qgbyk=,tag:CETj8Vl8HaYlEliO2tUNWg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
