---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: action-runner
  namespace: gha
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: action-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: action-runner
    namespace: gha
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: action-runner
  namespace: gha
spec:
  roles:
    - os:admin