apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:813zW6chMtuBp9ojFFJyDioztHfSnsagJ9TWp3jSQXSrV+gQJj2PkRovn5UE/vFoLFvta8uBmx0JcKqADbyqwazgEaEEZFsKdZfST54sdAnJgVjEcPotUMbWY5ZJ,iv:LgPeCphozUv0SbMuiUe9MMz/W1xNMM6FKWoH9aA6cX8=,tag:zNTVWfmiONC3IfGy5Ql7qA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUkZyak5ONUwwMFBJMjdZ
            TW5HRnpzSS9JVTR2Zjk2Rmltam1DRUJabURvCkRVaFlkeHFBVGpDSy9Nc2FmaXV0
            YUpuSXNTMmp1Qk0yUFQ0a1JUVHpzNUkKLS0tIFNIczcvNnIyOXRJWk83eTR1a3RX
            enlWRGFqUlpIRW9TWHA2ZVNCcEYzdkUKYpMOVN9ZVDr4Jbx5djk+dtoqYJIv14ou
            153KWiWOkYvYMS9lXKTmlLYC2r6jkRP6nizRlf4EuKb7VaE/qw15wA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-21T15:22:57Z"
    mac: ENC[AES256_GCM,data:60bo0pzA6Dje1g7+gVDlD/wBXC1hqYGXj6Zth4jsLPG2NGoHfXLy9kL/DqqXQRnZ0dj/i/bsYnJujQVxCY/To/ADTntYItEtQDu+iWY0vB29gVARoPrV3L7H4B4UgdLF+1EJ7Oy97qvhIB22Q7UmQV3bU/lrSSB/e62Q/HuCllU=,iv:58UFfpp7XJ88v7Ppto1YFhsu+HouVgkrRqyXP8d3D7g=,tag:Q3ESTif4oaCIr5D/ze7UEQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
