apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:An9xe0vRhXnKLiv6cOGVwtvh48ep8gvrRDb5hA7BjKE2PGGve0Z728xxPN5w8ZQxHGTFPFf6OQ9yk9mRPhpG81A5a7bLnMjUybk4zwHCAmEm2HXwYCAb/qjTgM6R,iv:602TLwarNKE756FZFQ/3wxFCcTDEAusjeF2Gp1NRauQ=,tag:Hp3eoBRnkmw3ylyhis2LPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOU5sVER4NlhJY0ZEVkg2
            eVNvY1F6OHFNQlNxUllVZHFmWG9iQmJNdjM0CmVSc1h2VVlRRlJJcWJ1bDh5RGwr
            UUwzZHQybzA0YktJQ1FqZjNZa0NRdkEKLS0tIFRPWnQvWWV1T1dwMFozcStBNVcw
            S1c1dXFCMzRSSGI5NnZHdVU5VHJJa00KQTdeHNzRc5DVSHVss9j9pctWtiuetpe4
            oL2O/ntXqCbg0wejeC1a6r4eND38Mvz7QtCMEcCHDwQQpv30vybY5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-28T08:32:15Z"
    mac: ENC[AES256_GCM,data:5Za5TsxDh3jfh8s/w8EpN4W0u5oZ0UJmGYOK3IM70QGxzjjaPLeVW8kTEjWZFz/RIgyBZRaFA7C2980GhfbUWnkrWqB0JYdLju/QIOEB8mvr6sHmFPo/SnL1w1vaqoytchFpRHSDJ8JH14apgrtsYgrNBCs4DOhiOk4fW+tHk34=,iv:90qt92cbJ9MoN4ixv0wV8O7kjS/BB1KjaoO35IkZbFQ=,tag:rJZEFQeKrXZCxmfh+Vv3tg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
