apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RA+axTDhHLnLtqeaLcWGCrLUXI5z3qAJRtjeiUSRBCnJtU/BFtSqs9dkPuhvh36uI8qLPSjOv7EXyXZfUqngChs8HFY4Oxy3D66Yh/HXMRi4Sm6DY5oY+NR9htzA,iv:g5EDotYvOOs7KGYt4Fz6NPxeKYhR0pzO7SVEqtPP4zI=,tag:hbq/X6jWBCaGkkeTuQfMfQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcllvQjIyUUtwVkNwL1VM
            dy9LNS9UMWpoR2JOOTRkSzNGSjZ1bGMxelVzCmdNQnM5L0gvNmpSTkNYNGY0SHE0
            SUVOVVdUYW00M1dMK0hpNG9zcVlhMlUKLS0tIC96Q0tvcm0zQ29hVk9KN0licWkx
            NFphK3ErS3FpM3g0MGNuZmZnYzJxYmMK0vxtdDYvZwegbzaUPWpS/Csu02q/55R+
            hE5kCzEBxhITD2vQdKwgHml7muc1hgp03nz3tQM7Epp9XLx6BrjHsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T10:44:22Z"
    mac: ENC[AES256_GCM,data:itt9xkDpDKjrAedbkojBg3UhHeb9PLSiWpfK1/De5xzJqfIewv+cEQShp0z/+8nGy+7Io8i5vw2vKz84hU0EBmyzcU7p4n8oSwnI/E5yqYg1KGMwMoiDy1r2es5CTKHuc78if3CZhKxkG7nOvMD9TmfxtyqvFsuQGnrY7GbOris=,iv:rFSvGWr7yPDuOQsdGf4O3O7kE/IiTl29y3CLGCEOK40=,tag:sN/j06tUPjRWu6FCFkApmQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
