apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NKhGNSCCb8h2SUoZXMMlBsxPxd6Ux7tsoRdHhwnkJlmj92qQbznHMoBhp8zkUSMcE+nTlFSywjj6UaQbnYT7fkzH04i1NQFk0KQPZdS8B6mphQ/SVzi/92kCP2eG7JQkPyTJICGdzb1Xg5hgtC89+qjKvf1KOpGCt8FIRrXUQTogaxRGJYnLeJXxhIusp197jgqG6e6HrvBhKwYKlo/ztzBKSct7R3hPZVA6ZrHJPhm6Lu/UgATQZz1nX+aKe3utJTkgOn0HP+jWYLblhymXgFCJHLZAF60JKlnN/0J+a11pEczOLGIWtfbbhLbZt5hKOJKM5Ija5/Sn/kgaNLLQj5/BMP1tQ10t6u+k4CZL3svIaIthfxEc2BCVFcTJyyv8,iv:+NiXTQzwXsd20X/Xkqe1kNlu9jRU0PuMR3dsk00h55M=,tag:eZWZwKrX0o6tiNkEJxZ1NQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:U3shatlqVMPkHBSgUYqN8cNpd5xv5kdciiZNCXmNJpF76r6BPkpnz76DZJtA5SV8jvJePNlXMK06frfHIUb+tfeuzOCUh8xInB5k4wJPEifvGZmv3WveImcQac2E37h6uP2aWYqzVVjjmWLaWhBcT/CP4xjAyULwq4FvKKEPYePgCwyqe5utfIRbbaHlLOJCe6l4INNXTZY5NZo14l1a+EARiIm1s2tbUFwWRWkreOYb0GGz7WxDKYstwpOmp0wKGHrUD4CSTJmDwHVLXA==,iv:M+1ATdWzFcNOWYjo7fYZHSGTuO5KuoPaHPs3htznHRM=,tag:fzAkGoRFnUvsyywaLd1+0Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:nqZYFSgNry6nw3U2uwuyyFY1ydiD8i6bdtSAF/5xNh+Xdyl9KqO5yBocm1eXd7FKeZs0yNhUYhI3d+g3TKrbK3jbpoM84yeBxF20FbydpEJrDg2nNdnnqGKPcOqN8jTeALNW9tWShjpU/Hf6eS9Kg8vnCZXUMYiRmkb401aKLVgV8jdlZkvVry4h4q6ksf24bpnuH0FHkHCeqRLI+o3l30HdsnrV+eNzwZmO,iv:o0dsBwqosdtEVmgSc9sGNX+lJ9AjCR0VoGGrU7lsRfE=,tag:CKoZ+MgJk1G2DPbSI85MIg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEalMxcUlnRXlEOUZKbEVW
            R0xqZVo0SjdOQWY4SVJON2thdGFwTXFWSUZ3CjJQdXQxSmFqSWVrelNvS2Q1c3RH
            RWVPRk9aOGgyOW9xd0t1OHhuaXZGVU0KLS0tIDd1VENrd3V6QnRvTW9kOE9LVENw
            Vkt3dDQyaXNUMWxDWUM5dm5tTTFZMncKamOLuM0qyUHisTeKdePY1w7qSBCaG5W4
            BjMPR9kereyjv5HKwEHpkLf45vKDbLiMVfGy3xITADm5iLDnzQjepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T10:44:22Z"
    mac: ENC[AES256_GCM,data:Qp4shNTug4UXJvaUUIqwfgVI3kVMojTVw50C/mY+3yu+mj6rh3RpWRPB1boqFQg/aYGiIk9s2s03c32Sfvc6M+R92+EcVgJDl5Nhj16iQ0EksQewGNEN3jgd0GIpW8Oy2VUQafbAdKDam4bHL0OrMIlLr9by8ggfz5zuC38+IXk=,iv:0SCSRswilgcg+Wd5M1kJmA4VVrsHxh0M+hww66MJy6g=,tag:nPIFVogrxwtg/o1iD++nlg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
