apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fSXzqC6mY+Li5IyLMNRqF09OG2Y6ciB5kYDLOm2YjVrWsf0XcBTQuTSZ3v5R3LatpOiPwTqFHy7MVHiQ5e7yoc095+mm94GDnCK5jvwOvQcX8baDnbWDEU2gOlHWJG5uP2gzW/NGDTuhKu3dqLBxejqLyLWAotfI6EvVGecG0XmVUQYQGW6XW4qtJX+Sb8CB1sYs8yOhiZm7uYLXYCBpe3XMPgfwByz+fbiUrR7FHHUms7uVFsx18yuXT7N/vOLgVK5qFAGwo6nPH8iJjzc9TQp5iDyQC79pCTHmTHs98GJCKbGy+jSPgzQ6WeB4zlm+c1wZHonjN9UrBfyRbocpAv0f5MtLa15ng7Tqt4SMicTY4xiOZffxCaRDh8UJ6jfJ,iv:0lKJmIJIPDNTbbk9mfkJqzuQuxesgGFMUlFAEQk2Qkc=,tag:Kx+UCDHvQRD7dHb3Qf2XYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ryb1ZIM5PQ7232zo9j8P6tK0AOZSLVxAW+nBybf1JyZa4wfitIRNTn4ilOGublsvMA7Bk4mfhOyrbie2Al+6vB058wCX1cr47hZFT/1giucQWaRsZgk+zNyHIwf+za9MwRIjVGnCFEsjW1DGG47pwf0dCPRYmrOz41nrktuhWdV46TQe4AsWEG1suF+mrqHWJ6HKj2Zq6igWygV7DUk552CWHkf1b3T1KhGRMZ1/vNV76ICAWZWckMX4wmNiFhj/kp82vy5CyFlSrTGUAA==,iv:v+7zT/AvEbTOSTMphSR5wTrmM7ZhfBR1NPT2Kl5wNVY=,tag:2PoxwFSK0NnQK8DKYcNpbA==,type:str]
    known_hosts: ENC[AES256_GCM,data:9ug9rxMZVDBTjBvDD+UsyvaAZEbh7VUmgJJiFMlcDCvy9pAXMd94o3/SFaDBpAAKJ31dNVoEofbbVaEU1UNna4eqkhbanllHXTFYaEFe6gfNAub8XyIj1H/W/cCvZ9s8VVLtZUbRRWq6GjdvS3IYs6qgqBRrqS3e30bXhnkiR0/YyDxrsR6AbjMRb+RhT+nHObHYzeBevNniJp3VSWfRuFataJPVJfWKIJZc,iv:aJ0NLyTqvKbIhagzUD0GlUlWszEdlf803E2NHcdk7DM=,tag:c3ihvW99ujxVCxNBNrdd2g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUmM0cUc0MjlyaXp3LzJE
            VitTdFVIYXV3UkZhUXk1bi9waDFPMFB5RWhNCmRYdllEbmxSSFpyeHVRcTRTV0NW
            bHE0NTAxTllHL1o0YTd5cjZYTE9aQTQKLS0tIGk2SlUrdUhkKzBiUVljSmUvbTdI
            dWpRQnFXMGhRQVd5T2lTUk9LVHpRSHcKoQsWaA5m1+3yDoBnTZ5Qq53EdBUXJnXF
            Obxtr/LN3JGdVXuby5q0D+DFX5RFSuOtEzCIxmGfJTKvNwiwo2cXbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T11:28:12Z"
    mac: ENC[AES256_GCM,data:OP6gRk531tUwdB5+1UYqYeLFPxxVbA08Y1oqiFJk6cYYgiaPyF50UM/5w27IFagzXFEumZcn6FbJTxtjtBpd1ZhBMXnPFs5PE4CU3m8VtHDRaxgnYp9geyzBzrCaQr2I42p/0pQwOTokIpGrPynr8HhkmVTnygOxYo4LElWhLJk=,iv:rTr2siOHPijoiiBvDYhw5uWiiRmvYMdb9714vsU5yHQ=,tag:x/uqchUmrD/ZFps0kifxbg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
