apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:azZyQ8ycX7g12fFjgm4Ul13/+c+IByy8xTso12mAawRzKZQu6f23Kjy1hAhoQIVMrwrm0QLfqwWzouAIaGxYkHYOTXQHyWe9zNTNzQviSDSQctejImaYNOIVn5guQgKXn1NEpL0g5sxUB3k5K5rax+UZeR0W/r+bhv1BUNLpakLPcLDr0uvZ+RS4huK+CdqI5ImZVg88eIkAZODoxHv8N+nZwU92L+uWvJ514mish5Jnw7TN7pV/XIyphoj53nYImuR2n9MNVfT8mv24qyk3d0P0WtfV97qb0GutJKp13kF4RfeSnpQCJH+q/+FpowKokI/FQoaNrlopWsCQ7597n1AWITsFcMUpEpDJPJbsW/381fZfa/5GizA6c5+OsPlG,iv:MjxLrSehKDP7qDkI2A6N2zmHbUT0mmB19BU2l3NxdAg=,tag:rldr8ZUV06hfeYnnf9C2Kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:5EqrTgmkWJPvKJKXmqPD40rMLJ2oOHR8eTFXxKbyny4DZAtpDn8VUyMASgNwaPcI6r6ViU1m86vnjbwWZGnjHArdDDtD89GmNRO1ZJYlPZvRMqRFxNnrDESmIcUK8WpISxyC4HO8l6bpMC6fB9dcJbyVX1reXgr3BHGk7g6oTw4HFXjaYI+UarMorbVsbX48F1LH5SVu9DU6iGmmnGbHHlX0uXm3MaSIVFTOmVvmWJfwNJERqBYLT71zNrwUlLsnVOrMqGrEz76cUYnNkQ==,iv:P+vA7uhGVIiBpeuKDywe3pmMBy9mZBEg58k9ew4amjc=,tag:metg+9+Nem9W7OnatTdRHg==,type:str]
    known_hosts: ENC[AES256_GCM,data:3tzobwxgqdatDrBy/K1s39iPcfR2GouyJOV/4sQ127wbS2rBR/+wuwgexAbt1+GQh344blz1+0/rzRgDH6bzIlv3urG/RUVlb1vERCQu3YwgeT2ymNiht/wFW8oykCGYKvoXN5iP29R1pRos71qu3VF7My6h2lGFOmCL07xqTZS4NW4eDt4Ogrg/RHxfWWB0cTl4MovS+qi5ooqvBucEl4akOn5wW8ZkuGtT,iv:C1zS/k+GlzPAR3sLuTnZESssnxFMYrrvPBTsPhqsVpw=,tag:vuvaQpvOSoeBqFmIBL2Lhw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSG00dnRBZUV6ckU4Q09w
            UU8vU1YzV1FnQmF3bWFmbWFoYlE1aEMrbUI4CnltazZYeExLT3lTQit4T1NKSmpy
            NXRPZE9yejd5VTgyaWtLZ0xLN2FKdVUKLS0tIGZLYW1qRmhiMTNhY0M5UGZSenJL
            N2FTTkxIamQ0YnR2dFo1N2V6U0l4dEEKOc05fUOgYn7RVrdRR0JgBkRrPdbCF7Fr
            85v9IHTPLU0TwfOZM3/pyxMIzJNf/1M4ejXZcNmOPBl0qRaIKtEEgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-21T15:22:57Z"
    mac: ENC[AES256_GCM,data:faNTRig35sAOkN1w3GT9abzPS3QMrTC+yeXdvE2fXbCWm6a8zBMeD9oKene1EkGEj7Md4KrMDYNys5miChxf3wAhcjcUQzy9jGmX36Trin8I+aEyVHBUDLNCRipjuBEdBYVWlkU8qMJIKkFz8/KCm6tA3+1A6WjsPR8FSP0U00U=,iv:q1AzfYEU7uEZEJlfEToywU8qVU+QrO/11oocZbPXA7o=,tag:PMg7BTfIFFBY7WWvjZBohA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
