apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:zW3HzKBAHDwzykZuMd0YVAdJxvCYaFhY5sOMunCJB+hw6PEkvk7enHxia5eSIKLpndZdOCpJlDWFcyHMjfhar/su8nSN+s3UJ1YLdtqDR+Wo3S8RQCIex7vJ9d3CxWURBN6IuapSfdEUm7hqD+q5d0DgtRzLvvA/hA==,iv:22YBttAFep0LVC2WW9gSXp27jwh8ADriMjZGaXYoMJU=,tag:fHu9cY4FGiuhO+ZpAbM9DA==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:g0gKaUfa3EHXa0wzXYajYETc1Pt7y1H+eNRPpBbCAIH3iA23rJ7Oy/PSjpB7ZhGkVaYQPwj+D6x0oVr8XUf5KQ==,iv:XQG6jJQz6vyEZZLJr5pis5s7BqahgFHu7OcdiC29Iko=,tag:BwbfxxP8nDlXpucA64ku6g==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:yy0qDct8eor7c9tBAwHTC1k5eeR/eoRfUjdUfUNZ9CsRYBXKyGzL4w4xTb38xy2AeSP4dqsTB/jwOyKnTX1UKcKMLD9dxrGfQzGIOc7+PvNGN+KhKP9AS/NG8t0=,iv:PtZytO3cHae5O9G4mA+EPLc+7+inBLkJ2ZXlf20+K/4=,tag:rkLoM6JmSwlkEJfXsHnEvQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYXU0WFJxc1pablcrOVV5
            ZzBqR2c3SDBaR2oxZVZpZUNEb0dXZzhsMkFrClY2ZHZrcjdSZ1RJckUxbGFHUGJq
            d2R1aThONXM1WlNnb0kxdUhYb2NjcGMKLS0tIHNyZGVFUkNlSW8rcldOQXliOWN3
            dm9wZW5yWExxTG9hejQ4ZDg5MjdaVWcKUXHhht0yA43gIk8BrvsSzm4vClOxew8b
            6OaI0m/lW9mdhcLWnPNbrPwUaarjnCR19d8QtN0TW0Mz5RMwltdDTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T11:28:12Z"
    mac: ENC[AES256_GCM,data:gvAisyQWmQVigt/5yxAhG8oDHj0gGpCn+dBAaEI9dlEF3iDWlqGR7ZqC2oH6ZkHkjUW8fonMDTl178bE65ZvwHADSEO1zI8Y9r5+pRF7+bfYYKbhVMk9pGECSxvZ1ATeL5PXpX7mkfZFDEaFyS9nEEZ7jYDmTaFam2jlihxdK1w=,iv:OFtzWp+sqLsGFS0qucF/E6IPRHR/ZfzZhVcIDj3vM30=,tag:71GYodChiNIgH51ZOeqUXA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
