apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:YHNyk+ebXiZmT4jW6MACHag6rwiJop1cumFrRDy56cd+J0yPv44ZSNPI/X67Jzws+nWkGt0fH3QZ//XcZd9JHKCKh4jWL9SutXxG5b7rW7ZxDRsM2O/weB9IHkz7sfZVIzblNbveoOl9z32aL5YshAr0SZjw6UXAKg==,iv:8QF2Z0C9mIq1t5tnXrFCt1NqHBuSxeqeoN80ofSqKRc=,tag:bCzOOq7TqeNNzwlzzF5YXQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:n0+4ysDV/V1H9hqSuSqOftfgTFpR5xd+numRbLcvjyNgDWEx8eOv707gxFS1PIEoqIMcniWk9U57CuNgCTO7Lg==,iv:dnLpN3yRSvB0x13hKes2q8520Bj3GBey5Z422WrFQ+0=,tag:pjO6s+/m/lgKJuYODsI+6w==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:wkxH/rODDrdkec2guR3uVVnTjng4YbYWFQWeGWZrx03TkoE5TTFxRMW3TUNZF71dT5WRCNyAKTPFpJrxXKWK8hJdQN8XnbQEMnTVItQjqdyS/h5TMwA4jT2hW4c=,iv:t0GX2+OKPOMs8M5IbrMKYgJRvt56gf346M+Ljd3m6AM=,tag:uVBku28m4TkFMeniBWjHpA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYk9TUDdyNmVFOFpIWEpH
            ZkMxeEl6M1E4S3RxMHBwOWRNQ3YxMTFacDE0CmdQMjJmTXBHZTdCMW9PTkd4OTFr
            TXhGdmRhdG9zdmlZb013anl5SWl0VDQKLS0tIDBpdVlFY0pKeGJOZlpWVzM1Tjlr
            Q0ZNRFZEb0pMNTJwemFKZWU3UU9QckUK2+evPVJvQWqk0U4r+zmn9S0qgOmqoeMi
            avw/3ZBzp2Kfm6qzaf8wgVU6fWDeBEqrF6SNbgS1qB4YWGyO2NSaHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T10:44:22Z"
    mac: ENC[AES256_GCM,data:R9X6eunlk3v0BtdjZsaJ/gbLkuTxxBwTimBmBmt6p7qLuLha6ogZsPhCaMszeQyPuX8nnDVmgnpHtcILO2yi5WH+bRpl0IVjqssc3a31ih5QNK4tGFyKP4fqdj+r3SJugEsFEGonb7Iy18+QLX3w1GsBV0jnLJCDh4EnwFV/Y1M=,iv:r6xD+c7TGieoal1SnhFq7Ja20vLce2daJQsBNXwMDfI=,tag:GBQQqKpFRHcZfiSz67UNLA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
