---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runners-truecharts
  namespace: gha
spec:
  interval: 15m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    minRunners: 3
    maxRunners: 12
    githubConfigSecret: runner-secret-truecharts
    githubConfigUrl: https://github.com/trueforge-org
    controllerServiceAccount:
      name: actions-runner-controller
      namespace: gha
    containerMode:
      type: kubernetes
    template:
      spec:
        volumes:
          - name: config
            emptyDir: {}
          - name: tmp
            emptyDir: {}
          - name: work
            emptyDir: {}
        containers:
          - name: runner
            image: oci.trueforge.org/containerforge/actions-runner:2.334.0@sha256:b87dfdc4a93106061843d8a4ba3f2d4bf65c23040e61531f18280ada79f539fe
            command:
              - /home/runner/run.sh
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
            volumeMounts:
              - name: config
                mountPath: /config
              - name: tmp
                mountPath: /tmp
              - name: work
                mountPath: /home/runner/_work
