apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:K1n7pDPJecCEu4jXuJfzm+cvrB1ktm8ePh18631So1d/KmDP2kZH/MThpkXbINmgmtSl46h+ekuMezmfqqyHiWwzX8t1CTfBFAwwc5dCCpv2nATMo47ClkVzMT7Hdu3ZK7CkqlR0tsz2xFl3NxO1bF9THSGRg0czgg==,iv:jQaxBb2a5zFOG2ZS8IIH8dLurrLBZJL/v3gQ82YBobg=,tag:0hQjIr9EXaxxfoL1xEEN6Q==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:K5SFc6Qo1Cd0IPD+sGlYlXC1ackP2BIQ8HgvFoPozp5guLXkOWoBVcOOFLk/+C7HQsJ+gSSRY61aIOfIzyE6wQ==,iv:eI9SZB7/C3u8I5kjb5j34kgbm4H7wM3DiGbtLj95VW0=,tag:QjAn1+c/QOm0E7jJva4eCA==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:zgrc4tsn3X9BI3jaa4pb3quDpDjo2TkZ5tPiA3pp2vWS9gE2eiQmO6BL2e+kbo9drD1l32vcZysJv0HXHvDUSBUT5AWN36cU3KkinSWKMHHI547aiegX4RSY1r0=,iv:vC3IPpvE6nHOloPPfOwp+Dtsw5rGrmvLkLBuGSIyum8=,tag:n3VgAmnR+FBV7s+/JBq8qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKa3V6NUFpa0ovNG1YV1U1
            RVhrdkVDWk1zcVVhbGIrRTVIM2RpOUhHR1JrCml4dHA5SmM3OFY2bU0zLzFraFhK
            bUZHUC9MM00vZmg1MndKZnZlZWNtdTQKLS0tIDJrUEJEbi94UEJxOEFYMTYwNG5L
            SU8zY3dIcUV5a3c5YjRnK0k3cytITEUK6800ei0SLLgrWmxAZqK8fSGOa3ApTCv4
            /bWwL99oXHO8In+eMHJnbkCxqoQIXxX9dmZk3GueVx5KO6R3Jk5fTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-28T08:32:15Z"
    mac: ENC[AES256_GCM,data:qB3GC3Gxe4E0UF7mXQXQQvs3ank4AitY8VYPTllSCcCkdEUIK1OfPXDojWFxnNNNjCbHVBtSodm0G7vCzEdW5ljcN9PToVPGLmGi0CkiPtxM0ZWukclHjbLljaQqngPi997+Ud5aXpkxwzufFP+W6oCcBZDQG83hBI/6rIHn794=,iv:vc6ynlcED4ei/xLbTiVjgeqehUpq5RxUjuiCry+V17I=,tag:LJuejXKYLIqHStIPaSTlZw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
