apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:ElAYewiIQfBSUTPED36luoX3/w0NXOHHsQOq6SutO8QUU3lat5g7SHKlmZJmOrOWJ8PJCqzBPS4Whm5z55y4QffBkAWMOqKsiXRbWuHsAOYq95CMRxemHpGiCagphykWmlioD+TRqnEIj0zhAbdgWmQg55SfVUSPUw==,iv:R4IMWTaTJIDbZY3KfIGtJ8FE3EBTRuifVji5AQrOivo=,tag:E6LubmlCXSP35qQC0qBNjw==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:eTYFxBSb77oeTZzFgHNVVkgxHzXMw5rYMuo2YHo8u7ghdwbyerSsaZsDRSGAJSn4ZTULMZ6+HyppF2o/9NiSKQ==,iv:6c1y43sNHiObFTlSkiP9XQ6V5OUSpNkVnl9YuuCzG8g=,tag:qWWAQX+XMAs1qaOAZUE1uA==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:+HKxx1858lNZZJXGN3J4WEQX4VH9MRTVUanIMY16TVrS2wmhBlvEaAlM3W61bzlwZvXSLb9zfaJ54agYdLXn28qBeKe89iNJyLuRRkjDzSpB4xjv3Q2rqNvAFCo=,iv:8ZncB68oBO0uJ54TjBdBUrYaeVjF+hwgu+zdvCvvyo4=,tag:7Kj5LBSwzycERmBnnaQFhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRGI4SHphOE4yRnRmMUt0
            RVIycmdBZ1k1and3eVcwODVqN3c4YXVHMWpjCllGTWFWQkNQaW1Nb2JwUjhIS09J
            MHoxWU1qTjk5SEZrSUZnZUp0UVBhT0UKLS0tIGM1VHlnMm1OMU0wS2RKRWh1aUR5
            NG83NzRsOWV5ZUNIeHE4Q2c0ZXFVajgKjuZhkdx6ksMp8PKgl86CcqDxGsAJ0iyO
            VQ6mja19PDZFA2Es4Q8nJBV1U9fdV1iFlKMIRXMkgJ06NS4M/JCCVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-01T05:23:40Z"
    mac: ENC[AES256_GCM,data:5QjPGi00Ol9NBKSah2RtRwSpUa7H9HCI5Fikoa1A0HPOUp7l6lZHcJkZT2HB49jt5v8+f3Sey//PKdQf2kpmj6TeVOuVyaeX0QIR0tBb4WJoSU+w4ofbXEnoddogQPGR2PC5GvjdxSOAasRzeE8CAopa/3RXxUm0YXYDPe7tgN8=,iv:pxNZPc5fR7711E0ecwNHQXBWAN0N+L2/JapJCJ2aRr4=,tag:Xzl2uRd77qEOQY6xIyp7tA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
