apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:WU6g1XV67TGT2WX9ovEOe10COD+qomEWQEyL3n9MxNWIj0xPgbD0Z4dH8jSyak97GJ/5BT3c9bljsDGrtCBJAUyBfFYLfWTZU0TEuaLQ1nw7nQfujPGgzQgVEwTYEfeEnmMl66IkCf3HxyMzsjl05G9BnYGeJdD2aw==,iv:iVCA/5qA45ewrSdAuNu10SQrIgwRwAl8a108J5L9ROQ=,tag:DDZRejVIRNqmtUsUUVzc/A==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:E6L0sbvYslo1qHQPUmH7B0ZwBFutWTs6gF1LcPwndTTKM1IqphDxw5Np+d1plThguX3K3m7uSyfcd9gZp7vgAg==,iv:ARN6l7F6VYK6+lt7Y09hhX1rRn/EoJdenitA0m+CeJE=,tag:pruufx7QE5QIah2eEXu84Q==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:XmshpbrtTgYDNvfOPeNnoUzZHXH86rdJ4Q+DtH+84ZdRqZNkE43+DifEH/o1RzCFPnVQMRFOgfLl5GFXyJ0HVKSeHWVROxnmYDwvy9UgEmaWB0iCUw54tIyEN6c=,iv:en4oVhkGqOjWJrXkj9sMIdXN+aB9XSGpcgzxam+wp3s=,tag:FV4CkB2fQ6qzLhO7cKKTcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMkdZUytvU3JKS25LbVNr
            SHVtZ09nMUVUYjFjaStkdlJIMFlkTkM1K0RBClM2a3lXWjM5NkFVSWZtSU9idzVU
            cWhkekJLWVBpWlA2WGpnWU9XeXVESFUKLS0tIHdZamhlQW5DVXQxaVBIWi92WE94
            L0xiMG90VVpYSnU2QTZPbEtySU9HQUUKWbFsINcqnZBvKOPhdCIknZTSAWKcDq9P
            T9THEsfq6YDetdDr82kH612LckHrkuqxY5vt6jwHGpnduUPGf8s3Vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-21T15:22:57Z"
    mac: ENC[AES256_GCM,data:pWQJNEoQjvMZtezPmQkytnz686ItYL5mgU7U79r4V2m+iDuU4xV2xCw9u8s6wGz1CUI8cF4nz2DvQphpbLEseh03NjE7IAscnGaSRjixInlyhH2fO1BTnEXoM61xF0pbFzG1Ncg2I7DP/TJYmCV3UYMSilPGFxRsQBBHGtHsWU0=,iv:F1mFmNNtrKKAKnKKK5zTBo98wdw3S9u7IRCydevbrxU=,tag:oep7nzHvQXn0nR85/rgmtw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
