apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jts3servermod
  namespace: jts3servermod
spec:
  interval: 5m
  chart:
    spec:
      chart: jts3servermod
      version: 4.11.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "http://${S3_URL}"
        bucket: "${S3_BUCKET}-jts3servermod"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 20 0 * * *
      logs:
        volsync:
          - name: logs
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 20 0 * * *
    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          ingressClassName: internal
          hosts:
          - host: jts3servermod.${DOMAIN_1}
          integrations:
            nginx:
              enabled: true
              auth:
                type: "authelia"
                internalHost: "authelia.authelia.svc.cluster.local:9091"
                externalHost: "auth.${DOMAIN_1}"
            certManager:
              certificateIssuer: domain-1-le-prod
              enabled: true