apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-service-minio
  namespace: external-service
spec:
  interval: 5m
  chart:
    spec:
      chart: external-service
      version: 16.7.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    service:
      main:
        enabled: true
        externalIP: ${CONFIG_TRUENAS_IP}
        ports:
          main:
            enabled: true
            port: 10107
            protocol: http
        type: ExternalIP
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
        - host: minio.${DOMAIN_1}
        integrations:
          certManager:
            certificateIssuer: domain-1-le-prod
            enabled: true
