# Path of helm-release file to skip during CI testing
skipList:
  - clusters/main/kubernetes/kube-system/cilium/app
  - clusters/main/kubernetes/system/longhorn/app
  - clusters/main/kubernetes/observability/exporter-fritz/app
  - clusters/main/kubernetes/apps/renovate/app
  - clusters/main/kubernetes/system/spegel/app
  - clusters/main/kubernetes/auth/authelia/app
